### ISSUE TITLE
Actions not appearing in cue mapping

### ISSUE THREAD

**Issue by doglordington** [Premik/blender_rhubarb_lipsync_ng#11]
Thanks so much for your work on this!

Blender version - 4.0.2
OS - macOS Sonoma 14.3

I'm using the Mecaface add-on (https://mecabricks.com/en/shop/product/6), which creates a face rig with a set of preset poses in the asset browser / Actions.

The audio capture works fine. However, when I'm trying to map the saved poses to the capture cues, they do not appear as Actions with any of the mapping options (screenshot attached). Have tried multiple different ways to get this working but can't seem to figure it out, any help appreciated!

<img width="1512" alt="Screenshot 2024-01-03 at 11 41 50 AM" src="https://github.com/Premik/blender_rhubarb_lipsync_ng/assets/56972283/bd853a64-9b5a-4ce8-9cbf-61a5436e1f6b">

**Comment by Premik** [comment]
Hi @doglordington,
There was a bug in the `v1.1.0` where any empty Action in the sceene made the mapping drop-down break. Making it not showing any Actions. I don't see the screenshot you mentioned but I guess it could be the same issue. 
Please try again using [the v1.1.1+ of the plugin](https://github.com/Premik/blender_rhubarb_lipsync_ng/releases/tag/v1.1.1) where the issue is fixed.

**Comment by doglordington** [comment]
@Premik thanks for the reply. I tested with v.1.1.1+ but still didn't see any options in the mapping drop down

**Comment by Premik** [comment]
Might be another bug then. Can you please try to open the attached blend file to see if the drop-downs work there for you?
[simpleTest.zip](https://github.com/Premik/blender_rhubarb_lipsync_ng/files/13929566/simpleTest.zip)

![image](https://github.com/Premik/blender_rhubarb_lipsync_ng/assets/842962/add7a48e-d3e7-4861-8a97-a9bd8aa52363)

**Comment by doglordington** [comment]
@Premik - re-tested with the initial file and the Actions now populate in the drop down. It seems like the issue might be that I had not created a catalog for them in the current file, and they were in the "Unassigned" section. Recreating them and marking as pose assets allowed them to show up in the Mapping section.

I'm now having a different issue (this might be user error) - once I've baked the Actions to NLA, everything seems to work fine. However when I press Spacebar to play back the audio and lip-sync, nothing happens despite the actions being mapped to cues. The active strip mapping works, but the NLA strips don't actually cause changes to the rig to be saved and animated (hopefully that makes sense...)

<img width="1501" alt="image" src="https://github.com/Premik/blender_rhubarb_lipsync_ng/assets/56972283/ead9c6f3-ec3c-46b6-a821-9f55bf80f718">

**Comment by doglordington** [comment]
FYI - when I press "push down" in the action editor it seems like it fixed this issue! Marking as resolved, thanks Premik

**Comment by doglordington** [comment]
FYI - when I press "push down" in the action editor it seems like it fixed this issue! Marking as resolved, thanks Premik

**Comment by Premik** [comment]
Hi @doglordington ,
Glad you solved it out.

> ... marking as pose assets allowed them to show up...

This is not necessary. The plugin works with any action be it flagged as an asset or not. Perhaps Blender restart solved it? Maybe the plugin was not refreshed after the update correctly or something...

> ... I press "push down" in the action editor it seems like it fixed this issue! ...

You probably had an Action on your rig active in the Dope Sheet/Action editor. They override animation data from the NLA and are shown as a "pseudo" track in the NLA at the very top. The `Push down` (or `Stash`) button then removes active Action  from the selected Object and moves it at the bottom of the NLA stack to a new track. You could probably just unlink the Ation with `x`.
Very easy to get bite by this for people not familiar with NLA:  https://github.com/Premik/blender_rhubarb_lipsync_ng/issues/8#issuecomment-1793420480
