### ISSUE TITLE
No .exe file

### ISSUE THREAD

**Issue by Red-VFX** [Premik/blender_rhubarb_lipsync_ng#13]
In order to to click Capture it said I needed the rhubard.exe file, but it says It doesn't exist.

**Comment by Premik** [comment]
The `rhubarb.exe` comes with the plugin. Please check in the plugin preferences if the path is correct:
![image](https://github.com/Premik/blender_rhubarb_lipsync_ng/assets/842962/aea70e35-3067-4a94-bf8a-866caab29fa8)

If the path is correct pressing the `Check rhubarb version` button should show the executable version

**Comment by Premik** [comment]
@Red-VFX I assume it was the incorrect path to the executable file. If you are still having problems feel free to reopen the ticket or create a new one..
