### ISSUE TITLE
Can't Install 1.3.0 (Blender 4.1.1, Win10, RTX1080)

### ISSUE THREAD

**Issue by AGameWriter** [Premik/blender_rhubarb_lipsync_ng#15]
After Uninstalling 1.2.0, and installing the Zip for 1.3.0, I go to click the activation button...
<img width="394" alt="Capture" src="https://github.com/Premik/blender_rhubarb_lipsync_ng/assets/128440460/1cec84e6-0990-49a1-82dd-173b6787afc6">

...and get the following error message:
<img width="677" alt="Capture2" src="https://github.com/Premik/blender_rhubarb_lipsync_ng/assets/128440460/2d411d69-9a1a-49cf-ab12-d1be70b83929">
<img width="678" alt="Capture3" src="https://github.com/Premik/blender_rhubarb_lipsync_ng/assets/128440460/110b0aae-b751-4d96-add1-24a20a8e9a7e">

...and of a sudden, I can't seem to get 1.2.1 to re-install correctly either.
![8rmkk2](https://github.com/Premik/blender_rhubarb_lipsync_ng/assets/128440460/d7ade64e-744b-45c1-b35d-2a0c7687a741)

**Comment by Gh0StCK** [comment]
The same thing. Win10, RTX4070

**Comment by Premik** [comment]
@AGameWriter @Gh0StCK 
Can you please try the fresh [v1.3.1](https://github.com/Premik/blender_rhubarb_lipsync_ng/releases/tag/v1.3.1) if it is any better?

I forgot to run some linter tool so there was a test-import left in the main code. My bad.

**Comment by AGameWriter** [comment]
Looks like that worked for me. Leaving this open to your discretion since there was another user reporting.

**Comment by Gh0StCK** [comment]
> @AGameWriter @Gh0StCK Can you please try the fresh [v1.3.1](https://github.com/Premik/blender_rhubarb_lipsync_ng/releases/tag/v1.3.1) if it is any better?
> 
> I forgot to run some linter tool so there was a test-import left in the main code. My bad.

Yes, it seems to be working fine now. So far there have been no tasks to use the addon, but it starts without errors. Thanks!

**Comment by okikiola12** [comment]
> @AGameWriter @Gh0StCK Can you please try the fresh [v1.3.1](https://github.com/Premik/blender_rhubarb_lipsync_ng/releases/tag/v1.3.1) if it is any better?
> 
> I forgot to run some linter tool so there was a test-import left in the main code. My bad.

you still need to update your code in the next release.

i had these error, and other version where not installing.
![Screenshot_61](https://github.com/Premik/blender_rhubarb_lipsync_ng/assets/88362706/12adca47-049e-4b4a-8590-b6efc29324f6)
i had to reinstall blender before i can install the 1.3.1.

**Comment by Premik** [comment]
Hi @okikiola12 ,
sorry for the troubles. My understanding is you managed to install the new version eventually.

Reinstalling Blender seems like an over-kill. Perhaps cleaning the add-on folder manually or starting Blender with fresh profile would have been enough.  I have added an [Troubleshooting guide](https://github.com/Premik/blender_rhubarb_lipsync_ng/blob/master/troubleshooting.md) which describes those in more details.

**Comment by okikiola12** [comment]
> Hi @okikiola12 , sorry for the troubles. My understanding is you managed to install the new version eventually.
> 
> Reinstalling Blender seems like an over-kill. Perhaps cleaning the add-on folder manually or starting Blender with fresh profile would have been enough. I have added an [Troubleshooting guide](https://github.com/Premik/blender_rhubarb_lipsync_ng/blob/master/troubleshooting.md) which describes those in more details.

@Premik definitely, you should know I did those and it was when it persisted that I had to re-install blender again.
i know normally, when I delete the folder it should solve the issues but reverse was the case then.


That said, let me draw your attention to what I noticed here.

the previous version 1.2.1 or so,

I had a better output which is because the way the cues arrange themselves on the NLA. as seen here.

![Screenshot_24](https://github.com/Premik/blender_rhubarb_lipsync_ng/assets/88362706/b0e8038a-5d7c-40d9-bdc8-f699680b5734)
 however, the output of the last version is not good enough when compared to where we are coming from.
![Screenshot_21](https://github.com/Premik/blender_rhubarb_lipsync_ng/assets/88362706/15fc5418-5ef6-4efc-af68-d0ddf7a1fb3a)
 

now look at both.

![Screenshot_25](https://github.com/Premik/blender_rhubarb_lipsync_ng/assets/88362706/b944255f-2396-4bf9-a084-96a522cb95a8)

**Comment by Premik** [comment]
> @Premik definitely, you should know I did those and it was when it persisted that I had to re-install blender again. i know normally, when I delete the folder it should solve the issues but reverse was the case then.

@okikiola12 that is very strange indeed. The `BLENDER_USER_RESOURCES` folder is the only place where Blender stores any state as far as I know.  Hopefully it won't happens again :-) But if so, please also try to [start Blender with a Fresh profile](https://github.com/Premik/blender_rhubarb_lipsync_ng/blob/master/troubleshooting.md#run-blender-with-a-fresh-profile-factory-settings) first.

> I had a better output which is because the way the cues arrange themselves on the NLA. as seen here.

Can you elaborate a bit more what it means? I've aligned your screenshoots so the timelines match.
- The upper green box is the old version, blue is the new version.
- There are three black boxes between frames `~1758..~1776`  `C` `B` `C`, which indicates where the cue was detected.

![strips1](https://github.com/Premik/blender_rhubarb_lipsync_ng/assets/842962/ec11420d-92a6-4565-a491-5b967b28bbdc)

There are extra `X` strips added. This is result of the `Trim cues longer than` option in the `Strip Placement Settings` section. Set this to `0` to disable the trimming.

![strips2](https://github.com/Premik/blender_rhubarb_lipsync_ng/assets/842962/7f620280-8533-4cd7-803b-3b68dbd61fc4)

The cue ends (both start and end) now have bigger overlap. A strips starts to blend-in already when the previous strips starts fainting out:

![strips3](https://github.com/Premik/blender_rhubarb_lipsync_ng/assets/842962/ab888cd7-8634-4a6a-8674-66593d2055c2)

Related to the previous point, the strip influence is fully on the 100% only for roughly one frame duration And then it blends in or out. In the screenshot the  `B` and `C` were quite long. In the old version this would result in "freezing" of the face for several frames. In the new version they would be still slowly moving. Still not good but I hope it is better than freezing.

![strips4](https://github.com/Premik/blender_rhubarb_lipsync_ng/assets/842962/54460f45-3cd5-4e49-9857-1005ad5184df)

In the new version the overlap section length can't be directly controlled and it depends on the sibling strips lengths. Only the 100%-influence-frame point can be shifted more towards start or end of the strip using the `Blend In-Out Ratio`. 

Probably some additional control can be added to control the overlap length more directly, if you are getting better results with shorter overlaps.

**Comment by okikiola12** [comment]
@Premik the reason for the longer strip is that I untick this which make the output to even be better.
![Screenshot_27](https://github.com/Premik/blender_rhubarb_lipsync_ng/assets/88362706/dd33bf52-bca6-4a10-9d85-612df97905f8)
again, kindly compare this "Version 1.3.0"


https://github.com/Premik/blender_rhubarb_lipsync_ng/assets/88362706/b7619732-734a-4377-bc67-85bfa7f75305


the older "version 1.2.1"


https://github.com/Premik/blender_rhubarb_lipsync_ng/assets/88362706/7cb20625-5577-4f96-93dd-0719f2a8118f


so compare both.

for the 1.2.1 is better.

**Comment by Premik** [comment]
@okikiola12  I see. So you actually prefer the later video `pre2.mp4` from the `1.2.1` version where the overlap parts with blending are much shorter and there are more "still" frames. That is interesting, as to me the first one looks slightly better :-). Since the face is not "freezing" as much.

But now that I understand what you mean by "better," I can add some additional toggles to get the `v1.2` look back. Something to control the length of the overlap/blending region and still region. I'll think about it and add something into the new version.

**Comment by okikiola12** [comment]
@Premik what really matters is that the mouth movement should matches the cues/voices.
i understand you are looking at prevent stills, but there should be a way somehow.

Probably you might include rest position, of course you might say **A and X** is for that

**Comment by okikiola12** [comment]
@Premik , this error was thrown when clicking this play button on blender 4.2.

![Screenshot_13](https://github.com/user-attachments/assets/aba15e7d-65f8-4d20-92ac-efab7c5c1e7e)
 it seems the AnimData is read-only

**Comment by Premik** [comment]
Hi @okikiola12 ,

I don't think this is related to the Blender version. Did you perhaps have some NLA strips in `tweaking mode`? It is activated by the `tab` key, and the strip is then in green color. In the tweaking mode, Blender won't allow you to change/set the active action on the object. At least, that was how I managed to reproduce this error:


![image](https://github.com/user-attachments/assets/cbe19ec7-d741-477a-841e-3775c0d12fc1)

**Comment by okikiola12** [comment]
@Premik 
ok,you are right it there was some strips in the NLA.

any latest on this ?

![341815119-dd33bf52-bca6-4a10-9d85-612df97905f8](https://github.com/user-attachments/assets/3863cb1c-3dc9-458d-9480-28852deb910c)

**Comment by okikiola12** [comment]
it been a while friend
