### ISSUE TITLE
Fork partially working on Linux - no option for text document, "Sync time on select" goes to frame 0 and "place strip" problems

### ISSUE THREAD

**Issue by ShockBock** [Premik/blender_rhubarb_lipsync_ng#2]
Hi there,

Amazing work on what you've done with the fork so far, thanks a lot. Rhubarb is essential. :)

I've gotten the plug-in working on Linux Mint - up to a point. I can get the capture working on the speech audio file, but some of the keyframing is missing. I hand-'baked' the keyframes to an action strip by clicking on the outputs below the capture button generated by your fork and then applying the appropriate animation, as created by me, from Blender's new(ish) pose library. The keyframes that your fork suggested were perfect in terms of timing and choice of mouth shape. However, there were several that were missing. Do you plan to include the option to load in a text file, to support the audio file a user wishes to keyframe? As you know, this was available in the original version of Rhubarb.

Also, the fork's "Place as strip" function is placing the audio on frame 0, channel 128(!) of the VSE, regardless of the instructions I give it.

Having the outputs that are returned once one **captures** from audio work as buttons, which move the play-head to the appropriate place in the timeline is an excellent work-around whilst automatic mapping/baking is still in development. However, the time jumps between the keyframes are currently relative from frame 0, not where the relevant sound block is located in the VSE.

I'm sure these are all teething problems, though. You have on your hands a fork which could surpass the original in every respect.

**Comment by Premik** [comment]
Hi @ShockBock,
Thanks for the heads up and sorry for the delay.  I've released a new version which should be somehow more usable (hopefully).

>Do you plan to include the option to load in a text file, to support the audio file a user wishes to keyframe? As you know, this was available in the original version of Rhubarb.

If I understand correctly you are looking for the so called `Dialog file` option. This can be provided by pressing the down arrow button beside the `bake` button. I have not actually tested this option. So hope it would work for you..

![image](https://github.com/Premik/blender_rhubarb_lipsync_ng/assets/842962/13e27428-9229-4299-aa8f-729cd6d65732)


>Also, the fork's "Place as strip" function is placing the audio on frame 0, channel 128(!) of the VSE, regardless of the instructions I give it.

I believe this works as expected in the latest release. And the `start frame` is respected on all the relevant places. Including  the time-line syncing with the captured cues.
Note you need the remove/place the sound strip again if you change `start frame` later.

**Comment by ShockBock** [comment]
Thanks for the reply and update. Unfortunately, I couldn't get the latest version to work. I downloaded **blender_rhubarb_lipsync_ng-master.zip** and installed it within Blender, as per the last version, as a plugin. This seemed to go okay, if the message in the console is anything to go by:

`Modules Installed () from '/home/[myname]/Downloads/blender_rhubarb_lipsync_ng-master.zip' into '/home/[myname]/.config/blender/3.6/scripts/addons'.`

However, when I searched for the installed plugin using terms like 'rhubarb' and 'lipsync' to active it, it didn't show up.

EDIT: Running on Linux Mint.

**Comment by Premik** [comment]
Perhaps you have downloaded a source snapshot? The `blender_rhubarb_lipsync_ng-master.zip` file name looks suspicious. You need to download it from the [Releases page](https://github.com/Premik/blender_rhubarb_lipsync_ng/releases) and select the proper file based on your platform (`-linux`): 
![image](https://github.com/Premik/blender_rhubarb_lipsync_ng/assets/842962/bf515af5-bc27-43e2-b79b-a48acf9fce95)

**Comment by ShockBock** [comment]
Oops! Good catch, sorry about that. Okay, got the right file, but I've still got problems. From the console, when I try to enable the plug-in:

```
Traceback (most recent call last):
  File "/snap/blender/3763/3.6/scripts/modules/addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "/home/steve/.config/blender/3.6/scripts/addons/rhubarb_lipsync/__init__.py", line 34, in <module>
    rhubarb_lipsync.blender.auto_load.init(__file__)
  File "/home/steve/.config/blender/3.6/scripts/addons/rhubarb_lipsync/blender/auto_load.py", line 32, in init
    modules = get_all_submodules(Path(root).parent)
  File "/home/steve/.config/blender/3.6/scripts/addons/rhubarb_lipsync/blender/auto_load.py", line 65, in get_all_submodules
    return list(iter_submodules(directory, directory.name))
  File "/home/steve/.config/blender/3.6/scripts/addons/rhubarb_lipsync/blender/auto_load.py", line 71, in iter_submodules
    yield importlib.import_module("." + name, package_name)
  File "/snap/blender/3763/3.6/python/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/steve/.config/blender/3.6/scripts/addons/rhubarb_lipsync/blender/baking_operators.py", line 1, in <module>
    from lib2to3.fixes.fix_input import context
ModuleNotFoundError: No module named 'lib2to3'
```

I went into the filepaths mentioned in the error message above, deleted the folder created as the result of trying to install blender_rhubarb_lipsync_ng-master.zip and re-installed the correct file after a fresh reload of Blender, but still no joy. As I say, the above error message is what I get after that process.

**Comment by Premik** [comment]
Can you please try to [v0.9.1](https://github.com/Premik/blender_rhubarb_lipsync_ng/releases/tag/v0.9.1) now? 
I left some unused imports in place which were likely causing that error.

**Comment by ShockBock** [comment]
> Can you please try to [v0.9.1](https://github.com/Premik/blender_rhubarb_lipsync_ng/releases/tag/v0.9.1) now? I left some unused imports in place which were likely causing that error.

Good stuff, got it to install okay. I'm coming to the end of a project stage; the next time I'll need to lipsync is next week. I'll let you know how it goes then.

**Comment by Premik** [comment]
I believe the issue mentioned here has been already fixed. Please open a new ticket should you find any other issue or have any suggestion.
