### ISSUE TITLE
UI Missing in Windows 10

### ISSUE THREAD

**Issue by AGameWriter** [Premik/blender_rhubarb_lipsync_ng#5]
Hello, and THANK YOU for picking up the development on this addon.

Version 0.9.1
Windows 10
Blender 3.6.0

After installing and creating an armature with the requisite phoneme poses, I can't find the Rhubarb for Blender UI. See screenshot below.
I hope I'm just being dense! I've looked through all the various Properties tabs, but ![TRASHME](https://github.com/Premik/blender_rhubarb_lipsync_ng/assets/128440460/5e0d162b-0324-4f82-bf56-360d0398c896) is where I assume it should show up.

![BugRep_Missing_UI](https://github.com/Premik/blender_rhubarb_lipsync_ng/assets/128440460/443a9c3f-27a1-499a-bda0-294bfad65fc0)

As can be seen, I'm in pose mode, the addon is toggled active, and the poses exist. I assume the UI should be there even if the rig/assets aren't in place or set up correctly?

The only 'unusual' think I can think of in my .blend is, the image plane is not parented to the Armature, as I'm just controling the UV Mapping of UDIM tiles (via drivers in the Shader, I find the UV Warp modifier irritating). I didn't set up a whole character with a proper parent rig, etc.

**Comment by AGameWriter** [comment]
This maybe irrelevant, but I just noticed a warning when disabling and re-enabling version 0.9.1: 

> "This script was written Blender 3.40.0 and might not function (correctly), though it is enabled."

I tried running the archived version of 3.4.0 (not sure about "3.40.0") but the alert appeared there too, and I still couldn't locate the UI after activating the plugin.

![NewError](https://github.com/Premik/blender_rhubarb_lipsync_ng/assets/128440460/07153ad9-3a5c-43c2-8f96-053ade40f2bc)

**Comment by AGameWriter** [comment]
I hope all is well. I've continued poking around, but remain unable to access the plugin on Windows 10. I'd love to be able to help test its development!

**Comment by Premik** [comment]
Hi ,
Sorry for not coming back to you earlier. I really need to enable the github notifications..

>I assume the UI should be there even if the rig/assets aren't in place or set up correctly?

Correct. First I thought the plugin failed to install or register to Blender. But I can see it shows up in your Preferences.

Note the plugin UI is no longer in the Armature properties. The `Location` entry is misleading there. Something I probably forgot to change. 
You need to open the right-side tabs in the 3d view. Either by pressing the tiny `<` icon or by pressing **n** key (while mouse cursor is in the 3d view):

![image](https://github.com/Premik/blender_rhubarb_lipsync_ng/assets/842962/843ac27f-1a21-4e29-8601-edbef61e9d24)

I've just committed some quick-start documentation. Hopefully it would help too.

In case the Ui was still now showing up:
1. In the Preferences set the log-level to `TRACE`: 
![image](https://github.com/Premik/blender_rhubarb_lipsync_ng/assets/842962/84cb3dc1-12ad-436a-bf21-a032d99e1d45)

1.  Run [Blender from console](https://docs.blender.org/manual/en/latest/advanced/command_line/launch/index.html#command-line-launch-index) so the logs can bee seen.

1. Review the logs if there are any errors logged..

**Comment by AGameWriter** [comment]
I was, indeed, being dumb! I found it, and it seems to be working, although I'm having to wrap my braing around Actions and the NLE.

I was assuming it would apply locational keyframes to armature bones, but I'm happy as long as it works!

Much appreciated!

[0001-0280.webm](https://github.com/Premik/blender_rhubarb_lipsync_ng/assets/128440460/106ba5bd-89fb-4335-bc8d-72dd49ba2f54)
